application: blog2-150413
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /pics
  static_dir: pics

- url: .*
  script: blog.app

libraries:
- name: jinja2
  version: latest
